// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXjcgKMlkoww0hZvK180I__28kMneuvfI',
    appId: '1:885187497157:web:682323749124d63e3ef4ac',
    messagingSenderId: '885187497157',
    projectId: 'onlineshop-40200',
    authDomain: 'onlineshop-40200.firebaseapp.com',
    storageBucket: 'onlineshop-40200.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPYMfAUMS_NkrX4FXOrQYpwoXzR7n1aYg',
    appId: '1:885187497157:android:b0ce476f57c65ab53ef4ac',
    messagingSenderId: '885187497157',
    projectId: 'onlineshop-40200',
    storageBucket: 'onlineshop-40200.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRwMrHFvvqzv5h1T56Ut6Ydi99QDO5-Zk',
    appId: '1:885187497157:ios:3302edb13ffc30be3ef4ac',
    messagingSenderId: '885187497157',
    projectId: 'onlineshop-40200',
    storageBucket: 'onlineshop-40200.appspot.com',
    iosBundleId: 'com.example.onloneshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRwMrHFvvqzv5h1T56Ut6Ydi99QDO5-Zk',
    appId: '1:885187497157:ios:c4108cd303ef54953ef4ac',
    messagingSenderId: '885187497157',
    projectId: 'onlineshop-40200',
    storageBucket: 'onlineshop-40200.appspot.com',
    iosBundleId: 'com.example.onloneshop.RunnerTests',
  );
}
